#!/usr/bin/env python3
"""
detector_node.py
────────────────
ROS node that runs YOLO OBB inference on incoming camera images and publishes
oriented bounding box detections for the Otter USV.

Adapted from https://github.com/qq44642754a/Yolov8_ros to support OBB output.

Subscribed topics
-----------------
  <image_topic>              sensor_msgs/Image   — raw camera frames

Published topics
----------------
  <detection_topic>          ObbDetectionArray   — all detections per frame
  <viz_topic>                sensor_msgs/Image   — annotated frame (optional)

Parameters (loaded from detector.yaml via launch file)
-------------------------------------------------------
  ~model_path      str    path to best.pt
  ~image_topic     str    default /overhead_cam/image_raw
  ~detection_topic str    default /usv_detection/result
  ~viz_topic       str    default /usv_detection/image
  ~conf_threshold  float  default 0.35
  ~iou_threshold   float  default 0.45
  ~imgsz           int    default 960
  ~device          str    default "0"
  ~publish_viz     bool   default True
  ~viz_line_width  int    default 2
"""

import os
import sys

import cv2
import numpy as np
import rospy
from sensor_msgs.msg import Image
from std_msgs.msg import Header

# Ultralytics is available because this script runs under the yolo_training
# conda interpreter (see shebang).  Import after rospy so ROS errors surface
# first if the environment is wrong.
from ultralytics import YOLO

# otter_usv_detector messages — generated by catkin from msg/*.msg
from otter_usv_detector.msg import ObbDetection, ObbDetectionArray


# ─────────────────────────────────────────────────────────────────────────────

class OtterDetectorNode:

    def __init__(self):
        rospy.init_node("otter_usv_detector", anonymous=False)

        # ── Parameters ───────────────────────────────────────────────────────
        # model_path may be left empty (launch files normally override it with
        # $(find otter_usv_detector)/models/best.pt). Fall back to that package
        # path so the node stays portable even without an explicit override.
        model_path       = rospy.get_param("~model_path", "")
        if not model_path:
            import rospkg
            pkg_dir = rospkg.RosPack().get_path("otter_usv_detector")
            model_path = os.path.join(pkg_dir, "models", "best.pt")
        image_topic      = rospy.get_param("~image_topic",      "/overhead_cam/image_raw")
        detection_topic  = rospy.get_param("~detection_topic",  "/usv_detection/result")
        viz_topic        = rospy.get_param("~viz_topic",         "/usv_detection/image")
        self.conf_thr    = rospy.get_param("~conf_threshold",   0.35)
        self.iou_thr     = rospy.get_param("~iou_threshold",    0.45)
        self.imgsz       = rospy.get_param("~imgsz",            960)
        device           = rospy.get_param("~device",           "0")
        self.publish_viz = rospy.get_param("~publish_viz",      True)
        self.line_width  = rospy.get_param("~viz_line_width",   2)

        # ── Load model ───────────────────────────────────────────────────────
        if not os.path.isfile(model_path):
            rospy.logfatal(f"[detector] Model not found: {model_path}")
            sys.exit(1)

        rospy.loginfo(f"[detector] Loading model: {model_path}")
        self.model  = YOLO(model_path)
        self.device = device
        rospy.loginfo(f"[detector] Model ready — task={self.model.task}  "
                      f"classes={self.model.names}  device={device}")

        # ── ROS I/O ──────────────────────────────────────────────────────────
        self.pub_det = rospy.Publisher(detection_topic, ObbDetectionArray,
                                       queue_size=5)
        self.pub_viz = rospy.Publisher(viz_topic, Image,
                                       queue_size=5) if self.publish_viz else None

        rospy.Subscriber(image_topic, Image, self._image_cb, queue_size=1,
                         buff_size=2**24)

        rospy.loginfo(f"[detector] Subscribed to '{image_topic}'")
        rospy.loginfo(f"[detector] Publishing detections on '{detection_topic}'")
        if self.publish_viz:
            rospy.loginfo(f"[detector] Publishing viz on '{viz_topic}'")

    # ── Callback ─────────────────────────────────────────────────────────────

    def _image_cb(self, msg: Image):
        """Received one camera frame — run inference and publish results."""
        try:
            bgr = self._imgmsg_to_bgr(msg)
        except Exception as e:
            rospy.logerr_throttle(5.0, f"[detector] image conversion error: {e}")
            return

        h, w = bgr.shape[:2]

        # ── Inference ────────────────────────────────────────────────────────
        results = self.model.predict(
            source=bgr,
            imgsz=self.imgsz,
            conf=self.conf_thr,
            iou=self.iou_thr,
            device=self.device,
            verbose=False,
        )

        # ── Build detection message ───────────────────────────────────────────
        det_array = ObbDetectionArray()
        det_array.header       = msg.header
        det_array.image_width  = w
        det_array.image_height = h

        result = results[0]

        if result.obb is not None and len(result.obb) > 0:
            # xywhr: [cx, cy, w, h, angle_rad]  shape [N, 5]
            xywhr   = result.obb.xywhr.cpu().numpy()
            confs   = result.obb.conf.cpu().numpy()
            classes = result.obb.cls.cpu().numpy().astype(int)
            # corners: [N, 4, 2]  pixel coordinates
            corners = result.obb.xyxyxyxy.cpu().numpy()

            for i in range(len(xywhr)):
                d            = ObbDetection()
                d.class_name = self.model.names[classes[i]]
                d.confidence = float(confs[i])
                d.cx         = float(xywhr[i, 0])
                d.cy         = float(xywhr[i, 1])
                d.width      = float(xywhr[i, 2])
                d.height     = float(xywhr[i, 3])
                d.angle_deg  = float(np.degrees(xywhr[i, 4]))
                # Flatten [4,2] → [8]
                d.corners    = corners[i].flatten().tolist()
                det_array.detections.append(d)

        self.pub_det.publish(det_array)

        n = len(det_array.detections)
        if n:
            rospy.loginfo_throttle(
                2.0,
                f"[detector] {n} detection(s) | "
                + "  ".join(f"{d.class_name} {d.confidence:.2f}" for d in det_array.detections)
            )

        # ── Visualisation ─────────────────────────────────────────────────────
        if self.publish_viz and self.pub_viz is not None:
            viz = self._draw_detections(bgr.copy(), det_array.detections)
            try:
                self.pub_viz.publish(self._bgr_to_imgmsg(viz, msg.header))
            except Exception as e:
                rospy.logerr_throttle(5.0, f"[detector] viz publish error: {e}")

    # ── Image conversion helpers (no cv_bridge — ABI incompatible with Py3.10) ─

    @staticmethod
    def _imgmsg_to_bgr(msg: Image) -> np.ndarray:
        """Convert sensor_msgs/Image to BGR numpy array without cv_bridge."""
        dtype = np.uint8
        img = np.frombuffer(msg.data, dtype=dtype).reshape(msg.height, msg.width, -1)
        if msg.encoding == "bgr8":
            return img.copy()
        elif msg.encoding == "rgb8":
            return img[:, :, ::-1].copy()
        elif msg.encoding in ("mono8", "8UC1"):
            return cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
        else:
            raise ValueError(f"Unsupported encoding: {msg.encoding}")

    @staticmethod
    def _bgr_to_imgmsg(img: np.ndarray, header: Header) -> Image:
        """Convert BGR numpy array to sensor_msgs/Image without cv_bridge."""
        out = Image()
        out.header   = header
        out.height   = img.shape[0]
        out.width    = img.shape[1]
        out.encoding = "bgr8"
        out.step     = img.shape[1] * 3
        out.data     = img.tobytes()
        return out

    # ── Drawing helper ────────────────────────────────────────────────────────

    def _draw_detections(self, img: np.ndarray,
                          detections: list) -> np.ndarray:
        """Draw OBB polygons and labels on a BGR image."""
        for d in detections:
            pts = np.array(d.corners, dtype=np.float32).reshape(4, 2).astype(np.int32)

            # Colour scales with confidence: dim green → bright green
            alpha = max(0.4, d.confidence)
            color = (0, int(255 * alpha), 0)

            cv2.polylines(img, [pts], isClosed=True,
                          color=color, thickness=self.line_width)

            # Corner dots
            for pt in pts:
                cv2.circle(img, tuple(pt), 3, (0, 0, 220), -1)

            # Label above the top-most corner
            top_pt  = pts[pts[:, 1].argmin()]
            label   = f"{d.class_name} {d.confidence:.2f}"
            (tw, th), bl = cv2.getTextSize(label, cv2.FONT_HERSHEY_SIMPLEX,
                                           0.45, 1)
            lx = max(0, int(top_pt[0]) - tw // 2)
            ly = max(th + bl + 2, int(top_pt[1]) - 4)
            cv2.rectangle(img,
                          (lx - 2, ly - th - bl - 2),
                          (lx + tw + 2, ly + 2),
                          color, -1)
            cv2.putText(img, label, (lx, ly - bl),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.45, (0, 0, 0), 1,
                        cv2.LINE_AA)

        return img

    # ── Spin ─────────────────────────────────────────────────────────────────

    def run(self):
        rospy.spin()


# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    try:
        OtterDetectorNode().run()
    except rospy.ROSInterruptException:
        pass
